apiVersion: v1
kind: Service
metadata:
  name: weathservice
spec:
  selector:
    app.kubernetes.io/name: weatherapp-weather
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP